### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by JvB94** [ngocnicholas/airtable.net#11]
Hi,

thanks for this extension. Its exactly what i'm looking for.

I try to install the extension by Nuget and got this error

Error		Could not install package 'Airtable 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

What i'm do wrong? Is a solution there?

Thanks

**Comment by ngocnicholas** [comment]
If the target framework of your project is of v4.5.2, you should use Airtable.net v0.9.3. 
Airtable.net v1.0.0 requires .NETFramework v4.7.2 as indicated in the Requirements section of the documentation.
