### ISSUE TITLE
Airtable planning to require TLS 1.2

### ISSUE THREAD

**Issue by erastl** [ngocnicholas/airtable.net#13]
https://support.airtable.com/hc/en-us/articles/360021216813

Airtable has indicated they are requiring TLS 1.2 in July 2019. I followed their instructions for testing, changing the AIRTABLE_API_URL constant in AirtableBase.cs to https://api-future.airtable.com/ and received the following error:

"An error occurred while sending the request. The underlying connection was closed: An unexpected error occurred on a send.
Authentication failed because the remote party has closed the transport stream."

I was able to figure out a way to force TLS 1.2 (by adding "ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;" somewhere before the client.SendAsync() in HttpClientWithRetries.cs), and confirmed that it does work against the testing endpoint, but wanted to make sure the issue was raised.

**Comment by ngocnicholas** [comment]
The code does not need to be changed to support TLS 1.2. What you need to do is to upgrade your .net framework to version 4.7 or later. Please see:
https://blogs.perficient.com/2016/04/28/tsl-1-2-and-net-support/
Furthermore, it is not considered to be a good practice to specify the TLS version in your code. Please see:
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

**Comment by erastl** [comment]
Going to 4.7 is not an option for us at the moment, so specifying TLS version is the next easiest solution, even if not best practice. This makes sense though, thanks for the information!
