### ISSUE TITLE
Support Batch Api Requests.

### ISSUE THREAD

**Issue by danielhuggins** [ngocnicholas/airtable.net#14]
Airtable has added to their API - Batch updates! I'd really like support for that. Would improve our upload speed 9 fold.

**Comment by EvanHahn** [comment]
I work on the Airtable API team.

Batch operations are in beta. While we expect the API to be stable, it's possible that it will change before release. I'd hate for anyone to have to do extra work, so I'd vote to wait on this until batch operations are out of beta.

**Comment by EvanHahn** [comment]
Batch operations have been fully released! Feel free to start work on this, as our API should now be stable.

**Comment by ngocnicholas** [comment]
Batch updates feature added and published in nuget.org: Airtable.1.1.0.nupkg

**Comment by EvanHahn** [comment]
Great! Thanks for the timely response.
