### ISSUE TITLE
Not issue - but query

### ISSUE THREAD

**Issue by ImShaneTurner** [ngocnicholas/airtable.net#17]
Hi there!

I'm trying to import records from my airtable.
How do I use the 'offset' variable?

I can successfully pull down data from tables that contain less than 100 records, but I'm not sure what an example 'string' would be for 'offset'. I've tried putting in things like "1", etc. but it doesn't work.

**Comment by ImShaneTurner** [comment]
I see in the documentation that 'offset' gets set via the response.Offset example. Whilst I'm able to get all 173 records on PC, when building to Android, it gets stuck in the while loop, and only retrieves 100. Will investigate, but closing issue to try work this out

**Comment by ImShaneTurner** [comment]
Hi there :) 

Sorry for re-opening! 
I've just relooked at the 'offset' issue from before, and I wanted to find out if there's perhaps something I'm doing wrong (or if there may be a limitation of my android build)?

On PC, I run my script to pull the records, and as you can see - it correctly applies the offset to retrieve the remaining 73 records.

![image](https://user-images.githubusercontent.com/54539334/65965422-e9146f00-e45e-11e9-8a97-a70e0fb82ed6.png)

Here's a screen of the application running on my PC: 
![image](https://user-images.githubusercontent.com/54539334/65965650-43153480-e45f-11e9-8c4b-9d2f55766433.png)

And here's the exact same code running on my phone... except it doesn't ever get the remaining records -despite applying the right offset.
![image](https://user-images.githubusercontent.com/54539334/65966121-f8e08300-e45f-11e9-903c-8c6c971ea97d.png)

Any ideas for why this may be?

**Comment by ngocnicholas** [comment]
This issue is not in the scope of Airtable.net. Please email support@airtable.com for help. Thanks.
