### ISSUE TITLE
Detailed error information not returned in 422 responses.

### ISSUE THREAD

**Issue by mistakenot** [ngocnicholas/airtable.net#2]
Errors such as validation errors aren't returned to the client. You just get an empty AirtableInvalidRequestException() returned.

This shouldn't be difficult to do as long as the error details are returning to you via the http response like they are when you use curl. If I find some time I might make the change and open a PR.

**Comment by mistakenot** [comment]
#3

**Comment by ngocnicholas** [comment]
Thank you. I merged your PR.
