### ISSUE TITLE
`DateTimeOffset` support.

### ISSUE THREAD

**Issue by techiedesu** [ngocnicholas/airtable.net#24]
Cannot cast field to `DateTimeOffset`, only possible cast to `DateTime`. I can write something like `(DateTimeOffset)(DateTime)record.GetField("SampleDate")`, but it looks weird.

**Comment by ngocnicholas** [comment]
Newtonsoft JsonConvert utility automatically detects strings that are formatted like dates and then deserializes them to DateTime. When you call GetField() it returns an object. The type of the object is DateTime so you can only cast it to DateTime first. Subsequently, when you cast a DateTime to a DateTimeOffset, it works but your offset will always be +00:00. Not useful and nothing we can do about it.
