### ISSUE TITLE
ListRecords<T> doesn't populate the Id of T

### ISSUE THREAD

**Issue by nohorse** [ngocnicholas/airtable.net#29]
I was hoping to use the sample code method of casing records to T and get the Id populated, but I think I need to do this more manually.  

                    Task<AirtableListRecordsResponse<Place>> task =
                        airtableBase.ListRecords<Place>(tableName: "Places", offset: offset);

                    var response = await task;

                    if (response.Success)
                    {
                        _places.AddRange(response.Records);
                        offset = response.Offset;
                    }

but the Id of my type is not getting populated.  so I need to add a pre-processing loop

                 if (response.Success)
                    {
                        foreach (var item in response.Records)
                        {
                            item.Fields.Id = item.Id;
                        }
                        _places.AddRange(response.Records);
                        offset = response.Offset;
                    }

**Comment by ngocnicholas** [comment]
The class <T> is used to encapsulate all Fields of a record of your table. The Id of the record is not a Field of the record. The Fields belong to the record and the Id also belongs to the record. The record Id is populated properly in the response. 
For instance: response.Records[0].Id is the Id of the first record.
