### ISSUE TITLE
Visual Studio 2015 NuGet Error

### ISSUE THREAD

**Issue by bonerchamp** [ngocnicholas/airtable.net#30]
Could not install package 'Airtable 1.1.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	

Documentation states min .Net 4.7.2 or higher, windows 10, and visual studio 2015 or higher.
I believe I met all those requirements. I've tried changing my project to .Net 4.7.2 or trying an older Airtable version and same error. Is there any way to properly install the Nuget Package without using VS 2017 (I would like to stick to 2015)?

**Comment by ngocnicholas** [comment]
The Target Framework of the Airtable package 1.1.2 is .NET Standard 2.0. 
Your error happened when you tried to install the package into a project that targets .NETFramework version 4.8. 
Can you try to change your project target to .NET Standard 2.0 and see if you still have an error?
The link below has some information that should help:
`https://docs.microsoft.com/en-us/dotnet/standard/net-standard`
The minimum platform that .NET Standard 2.0 supports is .NET Framework version 4.6.1. 
The build platform of the Airtable package has .NET Framework 4.7.2.

**Comment by ngocnicholas** [comment]
Issue closed due to no feedback from user.
