### ISSUE TITLE
Breaking Change in 1.1.3

### ISSUE THREAD

**Issue by mattgwagner** [ngocnicholas/airtable.net#34]
GitHub and Dependabot updated my private repo project that uses this library overnight, and it actually ended up breaking my app. Any table that has a space in the name, e.g. "Safety Tests" in my case, now do not load. I downgraded back to 1.1.2 to verify that this is the culprit.

https://github.com/ngocnicholas/airtable.net/commit/47d6461c76b102b5ef0bb9677534edc69d969af3

**Comment by ngocnicholas** [comment]
Will look into it and submit a fix soon. Thanks for reporting this breaking change.

**Comment by ngocnicholas** [comment]
Bug fixed in new released version 1.1.4.
