### ISSUE TITLE
[RetrieveRecord] return custom object like ListRecords

### ISSUE THREAD

**Issue by MDzyga** [ngocnicholas/airtable.net#37]
Hi,
Could you extend your paclkage by RetrieveRecord<T>?
It should be the same solution like ListRecords<T>.
Thanks

**Comment by ngocnicholas** [comment]
RetrieveRecord returns a record. What else do you want? Please elaborate.

**Comment by MDzyga** [comment]
I need method which return generic type like ListRecords<T>.
Currently I have to use JsonConvert to serialize response and deserialize on my type.

**Comment by ngocnicholas** [comment]
Added RetrieveRecord<T> as requested. Feature will be available in Airtable.net 1.1.5.

**Comment by MDzyga** [comment]
Thanks
