### ISSUE TITLE
More Code Necessary For Example?

### ISSUE THREAD

**Issue by davidshq** [ngocnicholas/airtable.net#4]
I've tried setting up the example you provided, but it seems some further code is necessary. Here is what I have at the moment:

    {
    class Program
    {
        static void Main(string[] args)
        {
            TestAirTable();
        }
        
        async static void TestAirTable()
        {
            string baseId = "Name of Base";
            string appKey = "appkeyishere";
            string offset = null;
            string errorMessage = null;
            var records = new List<AirtableRecord>();

            using (AirtableBase airtableBase = new AirtableBase(appKey, baseId))
            {
                //
                // Use 'offset' and 'pageSize' to specify the records that you want
                // to retrieve.
                // Only use a 'do while' loop if you want to get multiple pages
                // of records.
                //

                do
                {
                    Task<AirtableListRecordsResponse> task = airtableBase.ListRecords(
                        "TESTT",
                        offset,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null);

                    AirtableListRecordsResponse response = await task;

                    if (response.Success)
                    {
                        records.AddRange(response.Records.ToList());
                    }
                    else if (response.AirtableApiError is AirtableApiException)
                    {
                        errorMessage = response.AirtableApiError.ErrorMessage;
                        break;
                    }
                    else
                    {
                        errorMessage = "Unknown Error";
                        break;
                    }
                } while (offset != null);
            }

            if (!string.IsNullOrEmpty(errorMessage))
            {
                // Error Reporting
            }
            else
            {
                // Do something with the retrieved 'records' and the 'offset'
                // for the next page of the record list.
            }
        }
    }
    }

**Comment by ngocnicholas** [comment]
Solution: Make TestAirTable() function run in a separate task.  See code in last email reply.
