### ISSUE TITLE
Change Newtonsoft to System.Text.Json

### ISSUE THREAD

**Issue by Phalanx123** [ngocnicholas/airtable.net#40]
Possibly change Newtonsoft usage to System.Text.Json to reduce reliance on third-party libraries?

**Comment by ngocnicholas** [comment]
Will look into it. Thanks.

**Comment by Faeldor** [comment]
I'd avoid this if you're doing anything more than using Newtonsoft to deserialize. `System.Text.Json` only support reading Json at this time. For consistency sake I would stick with Newtonsoft until `System.Text.Json` catches up.

**Comment by ngocnicholas** [comment]
Microsoft is constantly improving System.Text.Json and there has been significant improvements between .Net Core 3.1 and .Net 5.0 and Microsoft has already started planning for .Net 6.0.
With the info above in mind, I'm planning to do the migration in the new release of Airtable.net.

**Comment by chris-ux** [comment]
Interested in this due to DateOnly and TimeOnly.

Newtonsoft.Json.JsonSerializationException: Error converting value to type System.DateOnly

I see that this PR #47 is a little less than a year old.  Is there any ballpark when to expect your next release?

**Comment by chris-ux** [comment]
Interested in this due to DateOnly and TimeOnly.

Newtonsoft.Json.JsonSerializationException: Error converting value to type System.DateOnly

Is there any ballpark when to expect your next release?

PR #47

**Comment by ngocnicholas** [comment]
Replaced Newtonsoft.json with System.Text.Json 6.0.2.

**Comment by mabead** [comment]
FYI: I tried to upgrade from 1.1.5 to 1.3 but the result does not work because my enum values can't be converted properly by System.Text.Json because this library does not use the `EnumMember` attribute. See https://github.com/dotnet/runtime/issues/74385 for more details.

I will therefore have to stay with 1.1.5 because of this change of dependency in the AirTable nuget 😢
