### ISSUE TITLE
look up tables

### ISSUE THREAD

**Issue by MannusEtten** [ngocnicholas/airtable.net#41]
in airtable you can have lookup tables so i will give an example:

table 1:
id - name - place - country
1 - adrian - paris - le france
2 - thierry - valence - le france
3 -kostas - athens - greece

table 2: country
abc - le france
def - greece

what happened if i use your library to read table 1 is the following:

1 - adrian - paris - abc
2 - thierry - valence - abc
3 -kostas - athens - def

how can I change this into the real values from the look up table?

**Comment by ngocnicholas** [comment]
Please go to to https://community.airtable.com to find your answer.
