### ISSUE TITLE
field id's

### ISSUE THREAD

**Issue by MannusEtten** [ngocnicholas/airtable.net#42]
your client heavily depends on field titles, i do use this but my customer regularly changes the field titles.
To make my integration more robust I would like to switch to use the field id, an id which starts with "fld".

do you support this? So I can do a query with "records from table x with fieldid's {fld1, fld2, fld3}" instead of "records from table x with fieldid's {name, city, country}?

It also applies to update and adding new records.

**Comment by ngocnicholas** [comment]
This should work already. Wherever the API accepts a field name, it's interchangeable with the field id. So in the Airtable.net documentation, "fields" is an array of strings, where each string can be a field name OR field id. However, the field names, not the field ids, are still used in the records returned by the Airtable API.
