### ISSUE TITLE
CreateMultipleRecords Method Documentation

### ISSUE THREAD

**Issue by franpossetto** [ngocnicholas/airtable.net#43]
https://github.com/ngocnicholas/airtable.net/wiki/Documentation#CreateMultipleRecords-method

there is an small error in the sample that the documentation provides:

 **CreateMultipleRecords** Method has this line:
`AirtableRecord[] records = response.Record;`

but should have this line
`AirtableRecord[] records = response.Records;`

**Comment by ngocnicholas** [comment]
Corrected document. Thanks.
