### ISSUE TITLE
Get list of columns by table name

### ISSUE THREAD

**Issue by MDzyga** [ngocnicholas/airtable.net#45]
Hi,
I know this subject was closed earlier but this could be really nice feature and a lot of developers could be really happy ;)
Currently I have to send request to get records and group Fields by key to get all possible option.
If you are not able to prepare this method, maybe you can change a response to always get all keys (currently I get fields with values).

**Comment by ngocnicholas** [comment]
This isn't possible with Airtable's REST API, and this API client is only for the REST API. To get a list of fields, I think you need to use their Metadata API: https://airtable.com/api/meta

**Comment by MDzyga** [comment]
Thanks
