### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by lamanna-dev** [ngocnicholas/airtable.net#48]
Good work on this project, however I have a suggestion.
The objects do not lend themselves well to crud operations.
eg, retrieve a list of records, update them, and send them back. This is because of the need to convert Fields into IdFields.
I would suggest an CreateOrUpdate method that accepts the retrieved object (after updating).

**Comment by ngocnicholas** [comment]
Would you please describe what you are proposing in a detailed example?
Currently we need the IdFields because I need to know which record(s) that the fields changes should apply on.
Thanks.

**Comment by lamanna-dev** [comment]
This method retrieves List<AirtableRecord>():
https://github.com/ngocnicholas/airtable.net/wiki/Documentation#listrecords-method
We then need to convert this list to idFields[] before calling UpdateMultipleRecords.
Would it not be better to have an UpdateMultipleRecords(List<AirtableRecord> records)?
Or if there was a CreateOrUpdate method that accepted List<AirtableRecord>, and updates the record if it has an ID, or creates it if it doesnt have an ID.

**Comment by ngocnicholas** [comment]
Will look into it after mid Feb.  Thank you.

**Comment by lamanna-dev** [comment]
FYI I got around this by creating a dynamic type , and if the airtable Id is assigned, use IdFields:
`
public dynamic GetAirTableIDFields()
        {
            dynamic f;
            if (AirTableID != null)
            {
                f = new IdFields(AirTableID);
                f.AddField("AirTableID", AirTableID);
            }
            else
            {
                f = new Fields();
            }

            f.AddField("fldEzA8xixGzVBJ4R", ID); //"LocalID"

            f.AddField("fldZGZhb442nQ9rcV", ProductName);//"ProductName"
}
`

**Comment by ngocnicholas** [comment]
CreateMultipleRecords(), UpdateMultipleRecords(), and ReplaceMultipleRecords() are overloaded in Airtable.net 1.2.0.  These newly added methods will take a AirtableRecord[] as one of their arguments.
