### ISSUE TITLE
Signing nuget assembly

### ISSUE THREAD

**Issue by max-maurice** [ngocnicholas/airtable.net#49]
Are there any plans to sign the assembly in the nuget package?

**Comment by ngocnicholas** [comment]
There is no plans for signing it. Sorry,

**Comment by ngocnicholas** [comment]
Still no plans for signing it.

**Comment by brinkdinges** [comment]
Understood. I just published the signed version:
https://github.com/CAD-Booster/airtable.net.signed
https://www.nuget.org/packages/Airtable.Signed/
