### ISSUE TITLE
Issue with Latest Version and System.Text.Json

### ISSUE THREAD

**Issue by mattgwagner** [ngocnicholas/airtable.net#52]
Hi! Thanks for the work you're doing on this wrapper, I reference it in a few projects.

Unfortunately, I've been referencing a floating version, e.g.    ```<PackageReference Include="Airtable" Version="1.*" />```

The last few days, I've been getting a large amount of this exception, which I am almost 100% sure is related to this breaking change in switching JSON libraries.

System.InvalidCastException: Unable to cast object of type 'System.Text.Json.JsonElement' to type 'System.String'.

**Comment by mattgwagner** [comment]
I guess my request is to take 1.1.6. as unlisted or removed, if that's a thing -- I know Nuget is supposed to be immutable. 

Then publish your newer changes as a 2.x release.

Please and thanks!

**Comment by ngocnicholas** [comment]
I would prefer to keep 1.1.6 Airtable.net for the reasn below:
https://github.com/ngocnicholas/airtable.net/issues/40
If you cannot work around your System.InvalidCastException please keep using Airtable.net 1.1.5. Once There is a new version of System.Text.Json with a fix for you I will update Airtable.net. Thanks for your report.

**Comment by mattgwagner** [comment]
Yeahhhh so, I respect that, as this is your package... but that's definitely not how semantic versioning works :-)

Adding a new dependency that breaks existing code traditionally would not end up in a patch release.

Anyway, close away, I'll pin to 1.1.5.
