### ISSUE TITLE
Expose http client or handler in constructor

### ISSUE THREAD

**Issue by Alikont** [ngocnicholas/airtable.net#56]
Hello,

AirtableBase class has internal constructor that has HttpHandler parameter.

I'd like to be able to pass my own http handler to AirtableBase in a public constructor.

- I'll be able to use it with IHttpClientFactory
- I'll be able to use Polly policies for throttling and retry

**Comment by ngocnicholas** [comment]
This is done in Airtable.net 1.2.0.
