### ISSUE TITLE
Unsupported unicode characters in fields and formula

### ISSUE THREAD

**Issue by murat-mehmet** [ngocnicholas/airtable.net#6]
We have got some unicode characters in the field names like 'ş' or 'ğ'. When I call ListRecords with a formula that contains such characters, I get a reply that says there's no such a field and the 'ğ' character is shown as '%u011f' in the error.

I tried calling it from browser and it works perfectly, the field exists and the api can find it.

**Comment by ngocnicholas** [comment]
This problem is fixed in Airtable.net 0.9.3 available in nuget.org as of today.
