### ISSUE TITLE
Support for Comments

### ISSUE THREAD

**Issue by PeteMatterfield** [ngocnicholas/airtable.net#61]
Comments are supported by the official API [here](https://airtable.com/developers/web/api/create-comment)

Is it possible to add support for comments? We've been relying on this c# implementation for many months. Thanks for your hard work!

**Comment by ngocnicholas** [comment]
Will look into adding support for comments.

**Comment by ngocnicholas** [comment]
Enhancements included in new release of 1.3.0.
