### ISSUE TITLE
New Airtable API Release

### ISSUE THREAD

**Issue by Timmeeehh** [ngocnicholas/airtable.net#62]
Hi! Thanks for all the work in this project! Is there a project planned for implementing the new API Release? If so I would be happy to contribute.

**Comment by louisdesmeytere-igx** [comment]
If you're going to implement the new API release, will you include the new authentication method with the Personal Access Token? Or is that for after the beta release?

**Comment by Timmeeehh** [comment]
The new authentication method will be necessary as the API key will be depreciated at some point.

**[Airtable API Docs](https://airtable.com/developers/web/api/authentication)**

> Note: After Personal Access Tokens and OAuth are no longer in beta, a deprecation timeline for User API keys will be announced. There will be a notice period of at least 12 months before the deprecation is enforced, per our [deprecation guidelines](https://support.airtable.com/docs/airtable-api-deprecation-guidelines). We recommend migrating as soon as possible - some new features (e.g., metadata API access) will be exclusive to personal access tokens and OAuth access tokens.

**Comment by PeteMatterfield** [comment]
FYI: The authorization header format didn't change. You can just replace the api key with your personal access token right now when making calls and it works just fine.

**Comment by ngocnicholas** [comment]
Will look into this soon. Thanks for the heads up.

**Comment by brinkdinges** [comment]
I can confirm that changing the API key to your personal access token works. That was easier than expected :) 

I had some trouble finding where to create a token, though. That's here: https://airtable.com/create/tokens

**Comment by Timmeeehh** [comment]
Nice! Has anyone looked into the **Fields to merge on** addition to the API?
<img width="605" alt="image" src="https://user-images.githubusercontent.com/102968988/221833758-08670af0-244e-4720-b1f8-317aeae6dca2.png">

**Comment by ngocnicholas** [comment]
Yes.  It will be in a new Airtable.net release next week.

**Comment by ngocnicholas** [comment]
Enhancements included in new release of 1.3.0.
