### ISSUE TITLE
returnFieldsByFieldId for single records as well as ListRecords

### ISSUE THREAD

**Issue by tobyduncombe-ic** [ngocnicholas/airtable.net#71]
Hi,

Thanks for your hard work maintaining this library. We've run into an issue where we'd like to depend only on fieldId of each record rather than the field names. Unfortunately, we need to use `AirtableBase.RetrieveRecord()` as well as `ListRecords()` and only the latter allows us to specify `returnFieldsByFieldId`

I can see [here](https://airtable.com/developers/web/api/get-record#query-returnfieldsbyfieldid) that it is supported in the airtable API. Is there any plan to add this functionality?

Thanks

**Comment by ngocnicholas** [comment]
This is my oversight.  AirtableBase.RetrieveRecord() will allow you to specify returnFieldsByFiedId in the next release coming out soon.

**Comment by ngocnicholas** [comment]
Fixed in 1.4.0
