### ISSUE TITLE
[feat] CancellationToken

### ISSUE THREAD

**Issue by sommmen** [ngocnicholas/airtable.net#84]
Hello,

It seems requests are not cancellable.
My app runs as a windows service which must cancel between a certain time, so i need any async calls to be cancellable. Could we add CancellationToken support to the client?

**Comment by sommmen** [comment]
@ngocnicholas let me know if you'd accept a PR for this :).

**Comment by ngocnicholas** [comment]
Added CancellationToken support in 1.5.0.
