### ISSUE TITLE
FIx the AirtableApiError!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by chaotang11** [ngocnicholas/airtable.net#86]
The detailed message is just like this: **Value is not an array of record IDs.**
No inner exception, no stack trace, no indication on which field is failing. Can you guys add more details to the error message?

**Comment by ngocnicholas** [comment]
This error message is provided by Airtable.  I think it's pretty clear.  The failed field is the one which should be an array of record IDs and the user passed in something invalid instead.
